apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: PCC52D03280B7034C
    access: proxy
    url: postgres:5432
    database: fraud_detection
    user: fraud_user
    secureJsonData:
      password: fraud_pass
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
    isDefault: true
    editable: true
